---
- hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:

  - name: run show ver
    ios_command:
      commands: show version
      register: output

  - name: output to file
    debug:
      var: output.stdout

  - name: copy to file
    copy: content="{{ output.stdout[0] }}" dest={{ inventory_hostname }}.txt
  - debug: var=after_vty.stdout_lines