## conditional when, to show hostname lab
---
- name: quick play from lab
  connection: network_cli
  hosts: 1800cpe
  gather_facts: false
  tasks:
    - name: Show the hostname
      ios_command:
        commands: "show run | i hostname"
      register: output

#    - debug:
#        var: output
#      when: "'r2' in output.stdout[0]"

    - name: Configure and Loop through interfaces conditional
      ios_config:
        parents:
          - "interface {{ item.name }}"
        lines:
          - "duplex {{ item.duplex }}"
          - "speed {{ item.speed }}"
      with_items:
        - name: FastEthernet5
          duplex: full
          speed: auto
        - name: FastEthernet6
          duplex: full
          speed: auto
      when: "'r2' in output.stdout[0]" 

      register: show_output