---
- name: TRY TO GET A COUNT OF NOT CONNECTED INTERFACES
  hosts: 1800cpe 
  connection: network_cli
  tasks:
  - name: SHOW COMMAND
    ios_command:
      commands:
      - show interface status | in notconnect
    register: output

#  - name: SHOW THE  STDOUT_LINES
#    debug: var=output.stdout_lines[0]
 
  - set_fact:
      count: "{{output.stdout_lines[0] | length }}" 
  - debug:
      msg: "Node {{ ansible_host }} , Free Interfaces {{ count }}"